### ISSUE TITLE
img2img not working?

### ISSUE THREAD

**Issue by XTRMsavage** [Elldreth/loopback_scaler#16]
I am trying to add more details using this script and this is what I am getting, what am I doing wrong?

![00003-2211765574](https://github.com/Elldreth/loopback_scaler/assets/90519573/63c0d084-5fbe-476d-8b27-165fb933a12a)

![img2img-0001-1898607634](https://github.com/Elldreth/loopback_scaler/assets/90519573/b5342bb6-035c-4709-900d-423ba6a88bba)

<img width="944" alt="image" src="https://github.com/Elldreth/loopback_scaler/assets/90519573/d4a4346b-3740-40a5-9c59-a15494db28fd">

**Comment by Elldreth** [comment]
Well, Contour is only useful is niche circumstances so I wouldn't bother enabling that.  Also, I'd start by leaving the Sharpness, Brightness, Color, and Contrast sliders at values around 1 to 1.25 as they can have a big effect on the final image.  As far as the other settings go, I would leave the original image size in the img2img settings because the loopback script will be increasing the image size every loop, so if you want to get your 512 x 512 image up to 1024 x 1024, just leave your img2img size at 512 and set your loopback_scaler sizes to 1024 width and 1024 height (or use scale and set it to 2 since it will multiple your size by 2).  Lastly, I find that starting at a lower resolution (like 512 x 768 or 512 x 512) gives great results and can save you time.  I hope that helps.

I hope you have better results with these setting changes.

**Comment by Elldreth** [comment]
_Here's an example:_

**I started with a 512 x 512 image in txt2img**
<img width="1024" alt="txt2img" src="https://github.com/Elldreth/loopback_scaler/assets/115911432/e961072f-e508-4a33-b816-7354b5bf4e95">

Then sent it to img2img..

**img2img settings**
<img width="557" alt="img2img_settings" src="https://github.com/Elldreth/loopback_scaler/assets/115911432/8d1e1faf-f5cf-494d-b9c7-b774bf840612">

**Loopback Scaler settings**
<img width="556" alt="looback_scaler_settings" src="https://github.com/Elldreth/loopback_scaler/assets/115911432/fc50c1b0-ce26-4ca2-a8ca-e05d6fab727f">

**Results**

_Before:_
![before](https://github.com/Elldreth/loopback_scaler/assets/115911432/b8c68efb-013c-44c2-8b0d-976f914b4864)

_After:_
![after](https://github.com/Elldreth/loopback_scaler/assets/115911432/c3b0d0aa-e08f-41cb-bd10-a582d0aaffff)

**Comment by Elldreth** [comment]
**Here is the same setup with 8 loops (instead of 4):**

![8loops](https://github.com/Elldreth/loopback_scaler/assets/115911432/c1fa6d34-d2c3-4f42-afaa-662b5f36e5a8)

**Comment by Elldreth** [comment]
**Using the same settings with a different prompt:**

_Before_
![bunny_before](https://github.com/Elldreth/loopback_scaler/assets/115911432/8ec25492-258f-43e1-b940-831ffa8a621a)

_After_
![bunny_after](https://github.com/Elldreth/loopback_scaler/assets/115911432/ba55045a-dc6e-4ad1-b545-6b7ce4233bee)

**Comment by Elldreth** [comment]
**Also, I took your image and ran it from 512 x 512 using CLIP Interrogate (for the prompt) with 4 loops and here's the result:**

![img2img-0012-1012080086](https://github.com/Elldreth/loopback_scaler/assets/115911432/15924372-854b-445b-8a33-dda2bb583dba)

**Comment by XTRMsavage** [comment]
Awesome, Thanks. Ok, so I did some tests and have a few questions, I hope you and help me. Also I am not good at coding so I apologize for any dumb questions in advance :)

1. Up-scaling - I want to upscale an image to 2000x2000, So put 2000 in maximum image width and height value inputs and left the use scale check box checked, but the image still came out 1024. Other settings were Loops 4, Scale final image 2.
2. I do these renderings and 3D model/ figure has to remain intact. How can I control that? do I have to use controlnet/ inpaint mask etc?

**Comment by Elldreth** [comment]
Loopback_Scaler is not an upscaler so much as it is used to increase detail and quality.  If you want to upscale, I would recommend using SD Upscaler script, SD Ultimate Upscaler, or Multi-Diffusion.  

Your best bet to maintain your 3D model aesthetic, it would probably be best to use some of the Controlnet options along with loopback scaler or other tools.
