### ISSUE TITLE
Ability to save each loop

### ISSUE THREAD

**Issue by sbuldan** [Elldreth/loopback_scaler#2]
This is a feature request rather than a bug, would it be possible to save each loop in future versions?

**Comment by Elldreth** [comment]
Unless I broke something in my last update the looper actually does save each loop to the samples_ouput directory.. for most people that's the /outputs/img2img folder.  I'll check it this weekend while I'm looking into the other issue posted.

**Comment by Elldreth** [comment]
I double-checked and it is still saving all the images in the /outputs/img2img folder.  That said, I have plans to add all those images to the final image preview so that you can more easily see the differences and select the one you want from the interface as opposed to having to pull them from a folder.

**Comment by Neverdusk** [comment]
I'd definitely love this as well. Sometimes I'll set a really high denoise to see what happens and catch a really cool result before it's replaced by something else. I don't have autosave enabled since I like to pick and choose the images I keep, so being able to see the loops in the final preview would be really helpful.

**Comment by sbuldan** [comment]
Thank you for the answer, I didn't realised it was saving. At least we hame something till we can see them in the preview.
